id = "odoo-js-snippets"
name = "Odoo Javascript Snippets"
version = "0.1.0"
schema_version = 1
authors = ["Ali Ns <aliimrandtb@gmail.com>"]
description = "OWL and JavaScript helper snippets for Odoo front-end work in Zed."
repository = "https://github.com/alienyst/odoo-snippets"
snippets = "./snippets/javascript.json"
