id = "odoo-python-snippets"
name = "Odoo Python Snippets"
version = "0.1.0"
schema_version = 1
authors = ["Ali Ns <aliimrandtb@gmail.com>"]
description = "Python-focused snippets for Odoo development in Zed."
repository = "https://github.com/alienyst/odoo-snippets"
snippets = "./snippets/python.json"
